[package]
name = "toonies-client"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "toonies-client"
path = "src/main.rs"

[dependencies]
toonies-common = { path = "../toonies-common" }
tokio = { workspace = true }
ratatui = "0.29"
serde = { workspace = true }
rmp-serde = { workspace = true }
uuid = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
futures = "0.3"
crossterm = { version = "0.28", features = ["event-stream"] }
