from toonies_common.config import DEFAULT_PORT, MAX_PAYLOAD_SIZE

DEFAULT_HOST = "0.0.0.0"
BROADCAST_QUEUE_SIZE = 256

__all__ = ["DEFAULT_HOST", "DEFAULT_PORT", "MAX_PAYLOAD_SIZE", "BROADCAST_QUEUE_SIZE"]
